ZgParametro:
    type: entity
    table: ZG_PARAMETRO
    id:
        parametro:
            type: string
            nullable: false
            length: 20
            fixed: false
            comment: ''
            id: true
            column: PARAMETRO
            generator:
                strategy: IDENTITY
    fields:
        descricao:
            type: string
            nullable: false
            length: 60
            fixed: false
            comment: ''
            column: DESCRICAO
        valor:
            type: string
            nullable: true
            length: 200
            fixed: false
            comment: ''
            column: VALOR
    lifecycleCallbacks: {  }
