ALTER TABLE `ZGFMT_ITEM_ORC_CONTRATO` 
DROP COLUMN `IND_CONTRATADO`;

CREATE TABLE IF NOT EXISTS `ZGFMT_ITEM_ORC_CONTRATO_FORNEC` (
  `CODIGO` INT(11) NOT NULL AUTO_INCREMENT,
  `COD_ITEM_CONTRATO` INT(11) NOT NULL,
  `COD_PESSOA` INT(11) NOT NULL,
  `QUANTIDADE` DOUBLE NOT NULL,
  `DATA_OPERACAO` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`CODIGO`),
  INDEX `fk_ZGFMT_ITEM_ORC_CONTRATO_FORNEC_1_idx` (`COD_ITEM_CONTRATO` ASC),
  INDEX `fk_ZGFMT_ITEM_ORC_CONTRATO_FORNEC_2_idx` (`COD_PESSOA` ASC),
  CONSTRAINT `fk_ZGFMT_ITEM_ORC_CONTRATO_FORNEC_1`
    FOREIGN KEY (`COD_ITEM_CONTRATO`)
    REFERENCES `ZGFMT_ITEM_ORC_CONTRATO` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ZGFMT_ITEM_ORC_CONTRATO_FORNEC_2`
    FOREIGN KEY (`COD_PESSOA`)
    REFERENCES `ZGFIN_PESSOA` (`CODIGO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;
