ALTER TABLE `ZGFMT_EVENTO_PARTICIPACAO` 
DROP COLUMN `VALOR`;

ALTER TABLE `ZGFMT_CONTRATO_FORMANDO` 
ADD COLUMN `COD_STATUS` VARCHAR(1) NOT NULL AFTER `COD_TIPO_CONTRATO`,
ADD INDEX `fk_ZGFMT_CONTRATO_FORMANDO_5_idx` (`COD_STATUS` ASC);

CREATE TABLE IF NOT EXISTS `ZGFMT_CONTRATO_STATUS_TIPO` (
  `CODIGO` VARCHAR(1) NOT NULL,
  `DESCRICAO` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_general_ci;


INSERT INTO `ZGFMT_CONTRATO_STATUS_TIPO` (`CODIGO`, `DESCRICAO`) VALUES ('A', 'ATIVO');
INSERT INTO `ZGFMT_CONTRATO_STATUS_TIPO` (`CODIGO`, `DESCRICAO`) VALUES ('C', 'CANCELADO');
INSERT INTO `ZGFMT_CONTRATO_STATUS_TIPO` (`CODIGO`, `DESCRICAO`) VALUES ('P', 'PARCIAMENTE CANCELADO');

UPDATE ZGFMT_CONTRATO_FORMANDO SET COD_STATUS = 'A';


ALTER TABLE `ZGFMT_CONTRATO_FORMANDO` 
ADD CONSTRAINT `fk_ZGFMT_CONTRATO_FORMANDO_5`
  FOREIGN KEY (`COD_STATUS`)
  REFERENCES `ZGFMT_CONTRATO_STATUS_TIPO` (`CODIGO`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


ALTER TABLE `ZGFMT_EVENTO_PARTICIPACAO` 
ADD UNIQUE INDEX `ZGFMT_EVENTO_PARTICIPACAO_uk01` (`COD_ORGANIZACAO` ASC, `COD_EVENTO` ASC, `COD_FORMANDO` ASC);
