UPDATE ZGFIN_ARQUIVO_TIPO SET IND_ATIVO = 1 WHERE CODIGO = 'C240';


CREATE TABLE IF NOT EXISTS `ZGFIN_ARQUIVO_REGISTRO_SEGMENTO_TIPO` (
  `CODIGO` VARCHAR(4) NOT NULL,
  `NOME` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`CODIGO`))
ENGINE = InnoDB;


INSERT INTO `ZGFIN_ARQUIVO_REGISTRO_SEGMENTO_TIPO` (`CODIGO`, `NOME`) VALUES ('T', 'TITULO DO DETALHE (INFORMAÇÕES DO BOLETO)');
INSERT INTO `ZGFIN_ARQUIVO_REGISTRO_SEGMENTO_TIPO` (`CODIGO`, `NOME`) VALUES ('U', 'INFORMAÇÕES DO PAGAMENTO DO DETALHE');

INSERT INTO `ZGFIN_ARQUIVO_VARIAVEL` (`CODIGO`, `VARIAVEL`,`DESCRICAO`) VALUES ('45', 'COD_CEDENTE', 'CÓDIGO DO CEDENTE (USADO NA CAIXA ECONÔMICA)');
INSERT INTO `ZGFIN_ARQUIVO_VARIAVEL` (`CODIGO`, `VARIAVEL`,`DESCRICAO`) VALUES ('46', 'COD_SEGMENTO', 'CÓDIGO DO SEGMENTO');
INSERT INTO `ZGFIN_ARQUIVO_VARIAVEL` (`CODIGO`, `VARIAVEL`,`DESCRICAO`) VALUES ('47', 'VALOR_LIQUIDO', 'VALOR LÍQUIDO CREDITADO');
INSERT INTO `ZGFIN_ARQUIVO_VARIAVEL` (`CODIGO`, `VARIAVEL`,`DESCRICAO`) VALUES ('48', 'VALOR_OUTRAS_DEPESAS', 'VALOR DE OUTRAS DESPESAS');


INSERT INTO ZGFIN_ARQUIVO_LAYOUT_TIPO (`CODIGO`,`NOME`,`COD_FLUXO`,`COD_TIPO_ARQUIVO`) VALUES ('BOL_T400','ARQUIVO DE RETORNO (TITULO DE COBRANCA) CNAB400','T','C400');
INSERT INTO ZGFIN_ARQUIVO_LAYOUT_TIPO (`CODIGO`,`NOME`,`COD_FLUXO`,`COD_TIPO_ARQUIVO`) VALUES ('BOL_T240','ARQUIVO DE RETORNO (TITULO DE COBRANCA) CNAB240','T','C240');

UPDATE ZGFIN_ARQUIVO_LAYOUT SET COD_TIPO_LAYOUT = 'BOL_T400' WHERE  COD_TIPO_LAYOUT = 'BOL_T40';


ALTER TABLE `ZGFIN_ARQUIVO_REGISTRO_TIPO` 
ADD COLUMN `COD_SEGMENTO` VARCHAR(4) NULL DEFAULT NULL AFTER `IND_OBRIGATORIO`,
DROP INDEX `ZGFIN_ARQUIVO_REGISTRO_TIPO_uk01` ,
ADD UNIQUE INDEX `ZGFIN_ARQUIVO_REGISTRO_TIPO_uk01` (`COD_TIPO_REGISTRO` ASC, `COD_TIPO_ARQUIVO` ASC, `COD_SEGMENTO` ASC),
ADD INDEX `fk_ZGFIN_ARQUIVO_REGISTRO_TIPO_2_idx` (`COD_SEGMENTO` ASC);

ALTER TABLE `ZGFIN_ARQUIVO_REGISTRO_TIPO` 
ADD CONSTRAINT `fk_ZGFIN_ARQUIVO_REGISTRO_TIPO_2`
  FOREIGN KEY (`COD_SEGMENTO`)
  REFERENCES `ZGFIN_ARQUIVO_REGISTRO_SEGMENTO_TIPO` (`CODIGO`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;


DELETE FROM ZGFIN_ARQUIVO_LAYOUT_TIPO WHERE CODIGO = 'BOL_T40';

INSERT INTO `ZGFIN_ARQUIVO_LAYOUT` (`CODIGO`, `COD_TIPO_LAYOUT`, `COD_BANCO`, `NOME`) VALUES (2, 'BOL_T400', 113, 'Layout de retorno de cobrança tipo CNAB400 da Caixa');
INSERT INTO `ZGFIN_ARQUIVO_LAYOUT` (`CODIGO`, `COD_TIPO_LAYOUT`, `COD_BANCO`, `NOME`) VALUES (3, 'BOL_T240', 113, 'Layout de retorno de cobrança tipo CNAB240 da Caixa');


INSERT INTO `ZGFIN_ARQUIVO_LAYOUT_CARTEIRA` (`CODIGO`, `COD_LAYOUT`, `COD_CARTEIRA`) VALUES (1, 2, 2);
INSERT INTO `ZGFIN_ARQUIVO_LAYOUT_CARTEIRA` (`CODIGO`, `COD_LAYOUT`, `COD_CARTEIRA`) VALUES (2, 1, 1);
INSERT INTO `ZGFIN_ARQUIVO_LAYOUT_CARTEIRA` (`CODIGO`, `COD_LAYOUT`, `COD_CARTEIRA`) VALUES (3, 3, 2);


UPDATE ZGFIN_ARQUIVO_REGISTRO_TIPO SET COD_SEGMENTO = 'T',NOME = 'REGISTRO DETALHE (SEGMENTO T)' WHERE CODIGO = 4;


INSERT INTO `ZGFIN_ARQUIVO_REGISTRO_TIPO` (`CODIGO`, `COD_TIPO_REGISTRO`, `COD_TIPO_ARQUIVO`, `NOME`, `IND_OBRIGATORIO`, `COD_SEGMENTO`) VALUES (13, '3', 'C240', 'REGISTRO DETALHE (SEGMENTO U)', 1, 'U');


INSERT INTO `ZGFIN_ARQUIVO_CAMPO_FORMATO` (`CODIGO`, `NOME`, `ALINHAMENTO`, `CHAR_PREENCHIMENTO`, `NUM_CASAS_DECIMAIS`) VALUES ('DT8', 'DATA 8 POSIÇÕES (DDMMYYYY)', 'D', '0', NULL);
